apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-helm
  namespace: mynamespace  # Changez le namespace ici
spec:
  releaseName: hello-world
  chart:
    spec:
      chart: test
      sourceRef:
        kind: HelmRepository
        name: hello-world-repo
      version: "1.0.0"  # Changez la version ici
      interval: 1m
  values:
    replicaCount: 3  # Modifiez le nombre de réplicas ici
    service:
      type: LoadBalancer
      port: 80

